### ISSUE TITLE
MDBNavbarToggler click event doesn't fire...

### ISSUE THREAD

**Issue by mainbranch360** [SauravKanchan/mdbsvelte#3]
Perhaps a misunderstanding on my part as to how it should work but it would appear that the click event for the MDBNavbarToggler doesn't fire. 

The example on the documentation page shows the same (lack of) behavior:

https://saurav.tech/mdbsvelte/?path=/story/navigation--navbar

**Comment by SauravKanchan** [comment]
Thanks for reporting this bug. This issue is now fixed(in version 0.3.2). Please update the package and try again.

**Comment by mainbranch360** [comment]
> Thanks for reporting this bug. This issue is now fixed(in version 0.3.2). Please update the package and try again.

Package updated and everything is working as expected. Thank you! Very nice package by the way!

**Comment by SauravKanchan** [comment]
> > Thanks for reporting this bug. This issue is now fixed(in version 0.3.2). Please update the package and try again.
> 
> Package updated and everything is working as expected. Thank you! Very nice package by the way!

Thank you
