### ISSUE TITLE
Explain differences from Sveltestrap and Bootstrap4

### ISSUE THREAD

**Issue by leejoramo-d51** [SauravKanchan/mdbsvelte#4]
Very interested in this project not having jquery. I assume this is the primary difference from Sveltestrap is the lack of jquery?

Is there anything missing from mbdsvelte due to the lack of jquery or other reasons?

https://github.com/bestguy/sveltestrap

**Comment by SauravKanchan** [comment]
+ sveltestrap is a wrapper of bootstrap4, so it will miss out on most of the material design like wave effects. 
+ components have more configuration when compared with sveltestrap. This project also include datatable which is missing from sveltestrap 
+ In sveltestrap you can't assign events(eg on:click) to all components. you can assign events to most of the components.
+ I am working on MDBsvelte dashboard which will be made using this library.
+ I am gonna add charts in few days.

**Comment by leejoramo-d51** [comment]
Thank you for the comparison. This moves mbdsvelte to the top of my evaluation list for a current project.
